### PR TITLE
fix: session store from issue #57

### PR DESCRIPTION
**Pull request by rsdeus**
This PR fixes the issue #57 by installing the activerecord_session_store - https://github.com/rails/activerecord-session_store.

### CODE REVIEW

**Comment by froger** [comment]
Hi @rsdeus I can't see any migrations files in this PR. I was expecting some after `rails generate active_record:session_migration` execution locally. Can you check this?

**Review by RCheesley — COMMENTED** [review]
Thanks for looking into this, could you share how it is possible to test? I guess it's a bit tricky given that it's quite a transient error which isn't affecting everyone.

**Comment by rsdeus** [comment]
> Hi @rsdeus I can't see any migrations files in this PR. I was expecting some after `rails generate active_record:session_migration` execution locally. Can you check this?

Sorry, here is the migration file
https://github.com/mautic/Community-Portal/compare/main...fix/session_store

**Comment by froger** [comment]
> Thanks for looking into this, could you share how it is possible to test? I guess it's a bit tricky given that it's quite a transient error which isn't affecting everyone.

Hi @RCheesley yes it is not really testable as it is. But I have reviewed and it looks fine to me. 
I am setting up a testing environment to be sure nothing breaks.

**Review by froger — APPROVED** [review]

**Pull request merged**
